"""Add file_path to artifacts

Revision ID: 8a9a8e2ac3b4
Revises: 015
Create Date: 2026-03-28 21:48:32.870825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8a9a8e2ac3b4"
down_revision: Union[str, Sequence[str], None] = "015"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artifacts", sa.Column("file_path", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("artifacts", "file_path")
    # ### end Alembic commands ###
